[package]
name = "cruel_game_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.23.1"
cgmath = "0.18.0"
egui = "0.31.1"
egui-winit = "0.31.1"
egui_glow = "0.31.1"
glow = "0.16.0"
glutin = "0.32.3"
image = "0.25.6"
winit = "0.30.11"
